### ISSUE TITLE
Question about adding in time as a field

### ISSUE THREAD

**Issue by chendw98-1664366** [paulo-herrera/PyEVTK#10]
Hi there,

I'm a student just heard of the file format. However, I didn't find much material about this. I want to visualization for a simulation and I want to generate an animation like video using paraview. So, I want to save the grid data in vtk format. However, I can't find the example in the example folder about how to add a time field, should it be passed in through "fieldData"? Also, may I check how do I represent the change of value on different points as time move on (like a 4th dimension for the point) by using this lib?
Really appreciate your time and looking forward to reply!
Thanks!

**Comment by xylar** [comment]
@chendw98-1664366 

This is something i do a lot for my work.  The way we handle time is to write out one `.vtp` per time step in a folder, and then create a `.pvd` file that knows where to find all of the `.vtp` files.  You don't have to use `.vtp`, you can use any of the XML file formats:
https://lorensen.github.io/VTKExamples/site/VTKFileFormats/#xml-file-formats
Here is some info on the PVD format:
https://www.paraview.org/Wiki/ParaView/Data_formats#PVD_File_Format
You can just write out these files yourself, something like:
``` python
...
# make a directory for the VTP files
try:
    os.makedirs('time_series')
except OSError:
   pass

# write out the PVD file
with open(`animation.pvd', 'w') as pvd_file: 
    pvd_file.write('<?xml version="1.0"?>\n')
    pvd_file.write('<VTKFile type="Collection" version="0.1"\n')
    pvd_file.write('\tbyte_order="LittleEndian"\n')
    pvd_file.write('\tcompressor="vtkZLibDataCompressor">\n')
    pvd_file.write('<Collection>\n')
    for time_index, time in enumerate(times):
        vtp_file_prefix = 'time_series/frame.{:d}'.format(time_index)
        pvd_file.write('<DataSet timestep="{:.16f}" group="" '
                              'part="0"\n'.format(time))
        pvd_file.write('\tfile="{}.vtp"/>\n'.format(vtp_file_prefix))
        # write out your vtp file
        ...
   pvd_file.write('</Collection>\n')
   pvd_file.write('</VTKFile>\n')
```
`times` is a vector of the time dimension and a float.  You can name your files and directories whatever you want.

Let me know if that gets you started.

**Comment by chendw98-1664366** [comment]
Hi @xylar 

Thank you so much!!! This helps a lot!

**Comment by chendw98-1664366** [comment]
@xylar  Hi there,

Sorry for a follow up question, I'm curious if it is possible to pass in a complex number as point value in this package? 

Thanks!

**Comment by xylar** [comment]
@chendw98-1664366, I have never tried but I very much doubt it.

**Comment by chendw98-1664366** [comment]
I see, I guess I'll need to find some other ways then, thanks!
