### ISSUE TITLE
v1.1.2 tag?

### ISSUE THREAD

**Issue by xylar** [paulo-herrera/PyEVTK#2]
@paulo-herrera, would you be willing to make a v1.1.2 tag of this repository?  I know not much has changed since v1.1.1 (nothing internal to the code) but this would allow @renefritze and I to make a new release on conda-forge and PyPI that points to the new location of your repository.  

Without a new version, we would have trouble bringing in your latest updates and it would be potentially very confusing if we were to change versions and got ahead of you (or out of sync).  Again, thank you!

**Comment by paulo-herrera** [comment]
Done.

**Comment by xylar** [comment]
Very much appreciated!
